//###############################################################################
//# WbXbc - Manual - Integration Parameters                                     #
//###############################################################################
//#    Copyright 2018 Dirk Heisswolf                                            #
//#    This file is part of the WbXbc project.                                  #
//#                                                                             #
//#    WbXbc is free software: you can redistribute it and/or modify            #
//#    it under the terms of the GNU General Public License as published by     #
//#    the Free Software Foundation, either version 3 of the License, or        #
//#    (at your option) any later version.                                      #
//#                                                                             #
//#    WbXbc is distributed in the hope that it will be useful,                 #
//#    but WITHOUT ANY WARRANTY; without even the implied warranty of           #
//#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
//#    GNU General Public License for more details.                             #
//#                                                                             #
//#    You should have received a copy of the GNU General Public License        #
//#    along with WbXbc.  If not, see <http://www.gnu.org/licenses/>.           #
//###############################################################################
//# Version History:                                                            #
//#   August 6, 2018                                                            #
//#      - Initial release                                                      #
//###############################################################################

= Integration Parameters

This section specifies the integration parameters to configure the WbXbc components.
Each WbXbc component supports a subset of the parameters listed below.

ITR_CNT:: The number of initiator bus interfaces to be offered by the WbXbc component

TGT_CNT:: The number of target bus interfaces to be offered by the WbXbc component

ADDR_WIDTH:: Width of all address busses (ADR_I and ADR_0)

ITR_ADDR_WIDTH:: Width of the initiator address bus(ses) (ADR_I), in case it differs
from the target address bus(es) (ADR_O) 

SEL_WIDTH:: Number data select lines of all initiator and target busses
(SEL_I and SEL_O)  

ITR_SEL_WIDTH:: Number of data select lines of the initiator bus (SEL_I), in case it
from the target bus (SEL_O) 

DATA_WIDTH:: Width of all data busses (initiator and target, read and write direction) 

ITR_DATA_WIDTH:: Width of the initiator's data busses (read and write direction

TGA_WIDTH:: Number of tags associated with the address busses of the initiator and
the target (TGA_I and TGA_O) 

TGC_WIDTH:: Number of tags associated with the cycle indicators (CYC_I and CYC_O) of
thw initiator and the target (TGC_I and TGC_O)

TGRD_WIDTH:: Number of tags associated with the read data busses of the initiator and
the target (TGD_O and TGD_I) 

TGWD_WIDTH:: Number of tags associated with the write data busses of the initiator and
the target (TGD_I and TGD_O) 

BIG_ENDIAN:: Selects the endianess of the design (1=big endian, 0=little endian)
